codacy/pulse-user-docs

docs/index.md
docs/metrics.md
mkdocs.yml
requirements.txt

The goal of this pull request is to do a first refactor of the "Integration guide" to make the instructions more linear and easy to follow.

Refactor and simplify documentation on how to push data

---

docs/index.md

Even though we cannot provide "straightforward recipes" that the users can follow step by step, we should provide enough background and guidance to allow the users to come up with solutions that are tailored to their specific infrastructure and workflows.

feature: Improve instructions on how to push data to Pulse

---

overrides/partials/integrations/analytics.html

Adds the tracking code for the **docs.pulse.codacy.com** [HotJar site](https://insights.hotjar.com/sites/2250360/dashboard).

feature: Add HotJar tracking code PUL-364

---

docs/cli/pushing-data-to-pulse.md
docs/one-click-integrations.md
mkdocs.yml

clean: Create link from documentation to integration page PUL-320

---

requirements.txt

This will fix the build of the docs.

bump: Update pymdown-extensions to latest version

---

README.md

This is because the name of the workflow file changed.

fix: Update MkDocs badge on README.md

---

docs/metrics/accelerate.md

This is just a first step to improving the reference documentation on the four Accelerate metrics before I organize/clean up a bit better the details on how we calculate each metric.

feature: Accelerate metrics descriptions PUL-477

---

.remarkrc
docs/metrics/accelerate.md

I refactored and simplified the page that includes the [reference for the Accelerate metrics](https://docs.pulse.codacy.com/metrics/accelerate/) to make it more systematic and easier to "parse" and understand.
Preview of the changes:
https://github.com/codacy/pulse-user-docs/blob/clean/review-accelerate-metrics-PUL-477/docs/metrics/accelerate.md

clean: Review and cleanup Accelerate metrics PUL-477

---

docs/metrics/accelerate.md

feat: Update docs with 2021 State of DevOps report

---

docs/cli/cli.md
docs/metrics/accelerate.md
docs/one-click-integrations/pagerduty-integration.md

feat: Make clear association between incidents and deployments

---

requirements.txt

Version details:
https://github.com/prcr/mkdocs-meta-descriptions-plugin/releases/tag/v1.0.2

bump: Update mkdocs-meta-descriptions-plugin from 1.0.1 to 1.0.2

---

docs/metrics/accelerate-changes.md
requirements.txt

feature: Mention that pending reviews are ignored

---

requirements.txt

Updates outdated requirements.
Fixes the broken CLI examples page:
* **Before:** https://docs.pulse.codacy.com/cli/examples/
* **After:** https://bump-update-requirements--docs-pulse.netlify.app/cli/examples/

bump: Update requirements

---

requirements.txt

chore(deps): bump mkdocs

---

mkdocs.yml

See [this comment thread](https://codacy.atlassian.net/browse/PUL-1228?focusedCommentId=51399) for more context.
https://infra-disable-instant-navigation-pu--docs-pulse.netlify.app/

infra: Disable instant navigation feature PUL-1228

---

.github/workflows/mkdocs.yml

Replicates the changes from https://github.com/codacy/docs/pull/1472 on this repository.

toolchain: Upload meta descriptions CSV file as an artifact

---

.github/pull_request_template.md

Adds a template for the description of pull requests created in this repository.

toolchain: Add template for pull requests DOCS-454

---

.github/issue_template.md

Adds a template for the description of new issues created in this repository.

toolchain: Add template for issues DOCS-460

---

.gitignore

Adds more rules to .gitignore configuration file.

toolchain: Add rules to .gitignore file

---

docs/index.md

this PR leverages the recent video demo from the BB announcement to provide an overview of the product, similar to quality's getting started page: https://docs.codacy.com/getting-started/codacy-quickstart/
https://feat-product-demo--docs-pulse.netlify.app/

feat: add 5 min video demo DOCS-469
