docs/index.md

I inadvertently removed this extra guidance on a previous pull request.
Although this simple solution does not work on Windows, to be fair, neither does running the CLI with the syntax `./event-cli`. We'll figure out a solution to provide guidance for Windows systems on a different iteration.

feature: Suggest using `date +%s` command to obtain Unix epoch timestamps

---

README.md

To simplify, for now I'm linking to already existing content on the [codacy/docs](https://github.com/codacy/docs) repository.

feature: Add minimal contributing instructions to README.md

---

docs/index.md
mkdocs.yml

Using the [Tabbed](https://facelessuser.github.io/pymdown-extensions/extensions/tabbed/) Markdown extension (with [built-in support](https://squidfunk.github.io/mkdocs-material/reference/content-tabs/) from the Material theme we are able to provide different instructions for Linux / macOS / Windows in a cleaner way:
With this solution we can also easily provide the command-line syntax for both *nix and Windows operating systems:
Yet another advantage is that this helps to reduce the overall length of the page.

feature: Use Markdown extension to provide instructions in tabs

---

overrides/partials/integrations/analytics.html

This ensures that we only need to maintain the Google Analytics tracking code in the centralized mkdocs.yml file.
(This is related with the change in https://github.com/codacy/pulse-user-docs/commit/e34ab2f8d14900bad12cc0cdb47977465a3c3f47.)

clean: Use Google Analytics config from mkdocs.yml

---

.remarkrc

I was finally able to configure the `.remarkrc` file so that the Visual Studio Code extension [Remark](https://marketplace.visualstudio.com/items?itemName=mrmlnc.vscode-remark) no longer increments the ordered list item markers.
(This pull request syncs the configuration with the one on the codacy/docs repository, see https://github.com/codacy/docs/pull/298.)

clean: Prevent remark-stringify from incrementing list markers

---

.codacy.yml
.github/workflows/mkdocs-deploy-gh-pages.yml
README.md

Adds nice badges to the README, similar to those on [codacy/docs](https://github.com/codacy/docs#codacy-documentation).
(The MkDocs badge will only show up correctly when the updated workflow runs for the first time on `master`.)

feature: Add Codacy and MkDocs README badges

---

overrides/partials/integrations/analytics.html

This should allow us to see the path users do from the app to the docs and back.
What do you think @pauloribeiro-codacy?

clean: Use same site as app.pulse.codacy.com

---

docs/one-click-integrations.md

Clarifies that the GitHub integration is able to provide data to calculate the new sub-metrics **Time to open** and **Time to review**:

feature: Mention Time to open and Time to review in GitHub integration PUL-392

---

mkdocs.yml
requirements.txt

Similar to Codacy docs.
During today's call, @rtfpessoa noticed it was hard to read the example code due to the ToC.
https://squidfunk.github.io/mkdocs-material/setup/setting-up-navigation/#navigation-integration

feature: Integrate ToC into sidebar

---

.remarkrc
docs/cli/examples.md
docs/cli/pushing-data-to-pulse.md
docs/metrics/accelerate.md
mkdocs.yml
requirements.txt

Enable and review meta descriptions for each Pulse documentation page.

feature: Enable meta descriptions for Pulse documentation pages

---

.github/workflows/mkdocs.yml

This step is necessary after all, since we're not fetching the entire Git history with the action actions/checkout.

fix: Fetch branch gh-pages before deploying docs

---

docs/cli/pushing-data-to-pulse.md
docs/index.md

The guidance to help users decide what they should send as the `system` only makes sense if they're using the CLI. When they're using the GitHub integration, we always use the name of the Git repository as the `system`, meaning that users don't need to make a decision themselves.

clean: Move guidance on what to send in "system" to CLI

---

docs/metrics/lead-time-reviews.md
docs/one-click-integrations.md

In an analogous fashion as https://github.com/codacy/pulse-user-docs/pull/55, this pull request does an overall review and cleanup to the documentation page covering the [Lead time and review metrics](https://docs.pulse.codacy.com/metrics/lead-time-reviews/).
This syncs the information with what's presented on the Pulse UI and presents the information in a more systematic way across the two pages that we currently have to cover the provided metrics. After this cleanup, let's discuss which improvements we want to make to the documentation and/or to the Pulse UI copy. :+1: 
Preview of the changes:
https://github.com/codacy/pulse-user-docs/blob/clean/review-ltr-metrics-PUL-477/docs/metrics/lead-time-reviews.md

clean: Review and clean up lead time and review metrics PUL-477

---

docs/metrics/work-in-progress.md
docs/one-click-integrations.md
mkdocs.yml

Adds descriptions for each metric that Pulse will present on the **Work in Progress** page.

feature: Add reference for work in progress metrics PUL-468

---

mkdocs.yml

In the landing page, we'll be using a new property with support for both V4 and Universal versions of GA in order to be able to use Google Optimize.
This moves the docs analytics to the same property as the landing page.
Depends on codacy/pulse#612

Change GA property

---

docs/cli/pushing-data-to-pulse.md

For now, this is the minimal update so that we include a link to the ingestion API reference documentation, instead of asking users to contact us for more info. Later we can give more visibility to the API (placing it on equal footing with the CLI, for example) if we find this relevant.
Preview of the updated page:
https://github.com/codacy/pulse-user-docs/blob/feature/link-api-reference-PUL-625/docs/cli/pushing-data-to-pulse.md

feature: Add link to ingestion API reference docs PUL-625

---

docs/metrics/lead-time-reviews.md
mkdocs.yml
requirements.txt

Updates the version of the plugin that allows generating meta descriptions from the intros of each page. Also adds a missing intro.

toolchain: Update mkdocs-meta-descriptions-plugin to 1.0.1

---

netlify.toml

Save Netlify build minutes by disabling builds on pushes to `master` since we're only using the service for previewing pull requests. :rocket: 
See https://github.com/codacy/docs/pull/821 and https://github.com/codacy/docs/pull/822 for a similar configuration on the codacy/docs repository.

toolchain: Disable unnecessary Netlify builds on pushes to master

---

docs/one-click-integrations/github-integration.md

I realized I find myself frequently needing to link to specific deployment strategies to advices users in support conversations.
Let me know if there is a better way of achieving it.

Make deployment strategies linkable headings

---

.github/workflows/mkdocs.yml

As of now, the build process for the Pulse docs is much simpler than the one for Codacy, but it's still a good idea to enable verbose output in line with https://github.com/codacy/docs/pull/1021.

toolchain: Activate verbose output for mkdocs build

---

docs/metrics/lead-cycle-time.md

Improves the introduction for the lead time and cycle time metrics, providing extra context to help explain the value of monitoring these metrics.
The information is based on our [recent blog post](https://blog.codacy.com/how-lead-time-can-improve-your-time-to-market/), which is also linked at the end of the introduction.

feature: Improve intro for lead and cycle time metrics PUL-842

---

mkdocs.yml

For some time, I've been feeling that it makes sense to promote the section "Calculated metrics" to the top of the navigation tree. I feel that this provides a more natural flow of the documentation since it provides context about the value of the metrics before providing instructions for setting up the integrations.

clean: Move Calculated metrics near the top of navigation tree

---

docs/cli/cli.md

For customers using GitHub, the Pulse GitHub Action is probably a more convenient way of reporting events to Pulse directly from their GitHub Actions workflows than running the Pulse CLI directly.
I decided to mention the Pulse GitHub Action right before the instructions for installing the Pulse CLI, as this is the place where users need to take the first step regarding setting up the reporting of events.
https://deploy-preview-96--docs-pulse.netlify.app/cli/cli/#1-installing-the-pulse-cli

feature: Mention the Pulse GitHub Action as an alternative to the CLI PUL-839

---

requirements.txt

Since it's not the first time that the MkDocs build starts failing because of Jinja2 updates, it's better to permanently pin this dependency and control when we get updates through Dependabot.
See also https://github.com/mkdocs/mkdocs/issues/2799.

toolchain: Pin Jinja2 dependency version

---

.github/workflows/mkdocs.yml
netlify.toml

This lets us overcome the 300 free CI minutes from Netlify since the builds are performed by a GitHub Actions workflow.
Applies the same change as the one from https://github.com/codacy/docs/pull/1165, https://github.com/codacy/docs/pull/1167, and https://github.com/codacy/docs/pull/1197.

toolchain: Build branch deploy previews using GitHub Actions

---

requirements.txt

After checking out the discussion on https://github.com/mkdocs/mkdocs/issues/2892, it seems that Markdown updates have some chance of breaking compatibility with mkdocs extensions.
Because of that, I think it's better to pin the Markdown version to ensure that we check that everything works fine on each pull request opened by Dependabot.

toolchain: Pin markdown==3.3.7

---

mkdocs.yml

I discovered that the meta Markdown [Meta-Data extension](https://python-markdown.github.io/extensions/meta_data/) is actually not needed since it's already included in MkDocs.
For more details, see https://github.com/squidfunk/mkdocs-material/issues/4179.

infra: Remove unneeded meta Markdown extension

---

docs/one-click-integrations/jira-integration.md

It's best to include both notes related to the Jira App installation in the same admonition card, otherwise, users may easily miss the note under the screenshot.

clean: Merge Jira App notes PUL-1281

---

.github/CODEOWNERS

Adds the techwriters team to CODEOWNERS file.

toolchain: Add techwriters team to CODEOWNERS DOCS-453

---

.github/workflows/mkdocs.yml

Replaces the `set-output` command, which is now deprecated: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
See also https://github.com/codacy/docs/pull/1473/.

toolchain: Update netlify-alias GitHub Action step

---

.github/workflows/enforce-labels.yml

Adds the workflow to prevent merging a pull request having the label "don't merge".

toolchain: Add enforce labels workflow DOCS-455

---

docs/one-click-integrations/github-integration.md

Clarifies that the information about the changes of a deployment must also be sent to Pulse when the option Detect deployments using GitHub is turned off.
https://clean-improve-gh-detect-deployments--docs-pulse.netlify.app/one-click-integrations/github-integration/

clean: Improve details for not detecting deployments automatically PUL-1409

---

docs/one-click-integrations/github-integration.md
requirements.txt

Adds a new table describing the permissions that Pulse requires from a GitHub organization and the corresponding purpose.
https://feat-gh-permissions-pul-1443--docs-pulse.netlify.app/one-click-integrations/github-integration/#gh-permissions
-   [x] Get all missing details from the team
-   [x] Request review

feat: Add permissions required for GitHub integration PUL-1443

---

docs/metrics/accelerate.md
mkdocs.yml
requirements.txt

Clarifies the heuristic that Pulse uses to match incidents and deployments, mentioning that the match only works for events sent for the same system, and repeats the note for both the **Time to recover** and **Change failure rate** metrics.
For context, see [this Slack thread](https://codacy.slack.com/archives/C019T4MJ1QX/p1668597349166979).
- https://fix-match-incident-deployment-pul-1--docs-pulse.netlify.app/metrics/accelerate/#time-to-recover
- https://fix-match-incident-deployment-pul-1--docs-pulse.netlify.app/metrics/accelerate/#change-failure-rate

fix: Clarify heuristic for matching incidents and deployments PUL-1423

---

docs/one-click-integrations/github-integration.md

For consistency across documentation pages, this PR:
* Matches the GitHub page to reflect the Bitbucket page edits on https://github.com/codacy/pulse-user-docs/pull/160
https://feat-match-bitbucket-edits-pul-1364--docs-pulse.netlify.app/one-click-integrations/github-integration/
-   [ ] Merge **right after** https://github.com/codacy/pulse-user-docs/pull/160

feat: Match GitHub page to reflect Bitbucket page edits

---

.github/workflows/jira.yml

Adds the GitHub Actions workflow to automatically create an issue on Jira for any new GitHub issues created on the pulse-user-docs repository.

toolchain: Add workflow to create a Jira issue DOCS-490

---

.github/workflows/jira.yml

After quickly testing the Jira workflow I realized that it wasn't working, but the solution to fix it should be quite simple, see https://github.com/codacy/pulse-user-docs/issues/168#issuecomment-1371302392.

toolchain: Set Jira labels as array of strings DOCS-490

---

.markdownlint.json

See https://github.com/codacy/docs/pull/1585 for the rationale behind this change.

toolchain: Disable markdownlint rule MD051

---

.github/workflows/mkdocs.yml

Updates the GitHub token used in the MkDocs workflow.

toolchain: Update GitHub token DOCS-455

---

.github/workflows/mkdocs.yml

Fixes a couple of details that we got wrong in https://github.com/codacy/pulse-user-docs/pull/179:
- The pull request previews can and should be performed using the `GITHUB_TOKEN`, otherwise, they appear as being made by the owner of the personal access token
- The GitHub action [peaceiris/actions-gh-pages](https://github.com/peaceiris/actions-gh-pages) actually [specifies a different input](https://github.com/peaceiris/actions-gh-pages#%EF%B8%8F-set-personal-access-token-personal_token) for using personal access tokens

toolchain: Fix using personal token in mkdocs.yml DOCS-455

---

.github/workflows/scheduled.yml
.lycheeignore

Adds the GitHub Actions workflow to run the following tasks automatically every Monday morning:
- Check for broken links pointing to external URLs and create an issue if there are broken links
- Run the [Calibre GitHub App](https://github.com/calibreapp/image-actions) and open a pull request to update any recently updated images with smaller file versions that look visually identical

toolchain: Add workflow for scheduled jobs DOCS-507

---

docs/metrics/accelerate.md

Adds a note for the **Time to recover** metric indicating that an incident report requires a previous deployment, otherwise, it's not considered by Pulse.
https://fix-add-note-for-time-to-recover--docs-pulse.netlify.app/metrics/accelerate/#time-to-recover

fix: Add that an incident report requires a previous deployment

---

.github/workflows/scheduled.yml

Applies the same changes as in https://github.com/codacy/docs/pull/1703.

 toolchain: Don't checkout submodules in scheduled workflows
